package com.enciyo.pinbook.utils

import com.enciyo.pinbook.domain.model.PopularBooks
import com.enciyo.pinbook.ui.books.models.CategoryModel


val dummyPopularBooks = mutableListOf<PopularBooks>(
    PopularBooks(
        "https://m.media-amazon.com/images/I/512qnExA+NL.jpg",
        "123",
        "2.4",
        "Metafizi",
        "21321"
    ),
    PopularBooks(
        "https://m.media-amazon.com/images/I/512qnExA+NL.jpg",
        "123",
        "2.4",
        "Metafizi",
        "21321"
    ),
    PopularBooks(
        "https://m.media-amazon.com/images/I/512qnExA+NL.jpg",
        "123",
        "2.4",
        "Metafizi",
        "21321"
    ),
    PopularBooks(
        "https://m.media-amazon.com/images/I/512qnExA+NL.jpg",
        "123",
        "2.4",
        "Metafizi",
        "21321"
    ),
    PopularBooks(
        "https://m.media-amazon.com/images/I/512qnExA+NL.jpg",
        "123",
        "2.4",
        "Metafizi",
        "21321"
    ),
    PopularBooks(
        "https://m.media-amazon.com/images/I/512qnExA+NL.jpg",
        "123",
        "2.4",
        "Metafizi",
        "21321"
    ),
    PopularBooks(
        "https://m.media-amazon.com/images/I/512qnExA+NL.jpg",
        "123",
        "2.4",
        "Metafizi",
        "21321"
    ),
    PopularBooks(
        "https://m.media-amazon.com/images/I/512qnExA+NL.jpg",
        "123",
        "2.4",
        "Metafizi",
        "21321"
    ),
    PopularBooks(
        "https://m.media-amazon.com/images/I/512qnExA+NL.jpg",
        "123",
        "2.4",
        "Metafizi",
        "21321"
    ),
    PopularBooks(
        "https://m.media-amazon.com/images/I/512qnExA+NL.jpg",
        "123",
        "2.4",
        "Metafizi",
        "21321"
    ),
    PopularBooks(
        "https://m.media-amazon.com/images/I/512qnExA+NL.jpg",
        "123",
        "2.4",
        "Metafizi",
        "21321"
    ),
    PopularBooks(
        "https://m.media-amazon.com/images/I/512qnExA+NL.jpg",
        "123",
        "2.4",
        "Metafizi",
        "21321"
    )
)

val dummyCategories = mutableListOf<CategoryModel>(
    CategoryModel("Felsefe"),
    CategoryModel("Tarih"),
    CategoryModel("Sanat"),
    CategoryModel("Psikoloji"),
    CategoryModel("Müzik"),
    CategoryModel("Kültür"),
    CategoryModel("Felsefe"),
    CategoryModel("Tarih"),
    CategoryModel("Sanat"),
    CategoryModel("Tarih"),
    CategoryModel("Sanat"),
    CategoryModel("Psikoloji"),
    CategoryModel("Müzik"),
    CategoryModel("Kültür")
)